### PR TITLE
update quiz results screen buttons

### PR DESCRIPTION
**Pull request by BRashad**
## Why was this PR opened?
- Add a check mark and cross to answer button in the Quiz Result Detail Screen

## Brief Description
The UI was missing correct and incorrect checkmarks on the button

## Unrelated Changes
I had to refactor the code on AnswerButton.jsx and QuestionCardResults.jsx by moving the conditional logic from the QuestionCardResults component to the AnswerButton component 

## UI Screenshots 
Screenshot 2023-08-31 at 10 53 05 AM
Screenshot 2023-08-31 at 10 54 12 AM

## Link to Referenced Trello Cards
https://trello.com/c/YaKvRYj2

### CODE REVIEW

**Review by georgekwan — DISMISSED** [review]
It looks like you haven't pushed the update for this PR
image

**Comment by BRashad** [comment]
Yes, indeed i pushed the update from the wrong location. now should be fine.

**Review by huynhtk80 — APPROVED** [review]
Looks good.  Only issue is that if the text is too long you don't see the check or X.  But this might be a separate styling issue that needs to be addressed.

**Comment by BRashad** [comment]
Yes maybe text should be wrapped

**Pull request merged**
